#!/bin/bash

export RUST_LOG="INFO"
export APP_ROUTES_HEALTH_PATH="/health"
export APP_ROUTES_HEALTH_METHOD="GET"
export APP_ROUTES_APP_PATH="/app"
export APP_ROUTES_APP_METHOD="POST"
export APP_ROUTES_APP_LATENCY="100"
export APP_ROUTES_APPLIST_PATH="/apps"
export APP_ROUTES_APPLIST_METHOD="GET"
export APP_ROUTES_APPGET_PATH="/app/{id}"
export APP_ROUTES_APPGET_METHOD="GET"
