#!/bin/bash

export RUST_LOG="INFO"
export APP_TARGETS__APPS__TARGET="http://localhost:8080/apps"
export APP_TARGETS__APPS__CLIENT_TIMEOUT="1500"
export APP_TARGETS__APPS__CLIENT_COUNT_RAMP="500"
export APP_TARGETS__APPS__CLIENT_COUNT_RAMP_INTERVAL="1000"
export APP_TARGETS__APPS__CLIENT_WAIT_START="0"
export APP_TARGETS__APPS__CLIENT_WAIT_JITTER="0"

export APP_TARGETS__APPGET__TARGET="http://localhost:8080/app/0"
export APP_TARGETS__APPGET__CLIENT_TIMEOUT="1500"
export APP_TARGETS__APPGET__CLIENT_COUNT_RAMP="500"
export APP_TARGETS__APPGET__CLIENT_COUNT_RAMP_INTERVAL="1000"
export APP_TARGETS__APPGET__CLIENT_WAIT_START="0"
export APP_TARGETS__APPGET__CLIENT_WAIT_JITTER="0"
